version: "3"

services: 
  frontend: 
      container_name: frontend
      build: ./u-social
      ports: 
          - '8080:8080'
    
  backend: 
    container_name: backend
    build: ./Backend
    expose:
      - "3000"
    ports: 
      - "3000:3000"