version: "3"

services: 
  frontend: 
      container_name: frontend
      build: ./u-social
      ports: 
          - '8080:8080'
      networks:
          - usocialapp
  backend: 
      container_name: backend
      build: ./Backend
      env_file:
        - ./Backend/.env
      expose:
        - "3010"
      ports: 
        - "3010:3010"
      networks:
        - usocialapp
networks:
  usocialapp:
    name: usocialapp
    driver: bridge
