version: "3"

services:
  backend:
      container_name: backend
      build: ./Backend
      image: brest12/usocial-api
      env_file:
        - ./Backend/.env
      expose:
        - "3010"
      ports:
        - "3010:3010"
  frontend:
      container_name: frontend
      build: ./u-social
      image: brest12/usocial-ui
      ports:
          - '8080:8080'
      links:
          - backend
